pipeline:

  install:
    image: quay.io/ukhomeofficedigital/node-10
    commands:
      - node -v
      - npm -v
      - npm install --silent
    when:
      event: push

  unit_tests:
    image: quay.io/ukhomeofficedigital/node-10
    commands:
      - npm run test
    when:
      event: push

  build:
    image: quay.io/ukhomeofficedigital/drone-docker
    commands:
      - docker build -t ref-data-gov-tool:$${DRONE_COMMIT_SHA} .
    when:
      event: push

  synch_dev_secrets:
    image: quay.io/ukhomeofficedigital/cop-secrets
    environment:
      - DRONE_SERVER=https://drone.acp.homeoffice.gov.uk
    secrets:
      - source: DEV_DRONE_AWS_ACCESS_KEY_ID
        target: AWS_ACCESS_KEY_ID
      - source: DEV_DRONE_AWS_SECRET_ACCESS_KEY
        target: AWS_SECRET_ACCESS_KEY
      - source: DRONE_PUBLIC_TOKEN
        target: DRONE_TOKEN
    when:
      branch: master
      event: push

  synch_staging_secrets:
    image: quay.io/ukhomeofficedigital/cop-secrets
    environment:
      - DRONE_SERVER=https://drone.acp.homeoffice.gov.uk
    secrets:
      - source: STAGING_DRONE_AWS_ACCESS_KEY_ID
        target: AWS_ACCESS_KEY_ID
      - source: STAGING_DRONE_AWS_SECRET_ACCESS_KEY
        target: AWS_SECRET_ACCESS_KEY
      - source: DRONE_PUBLIC_TOKEN
        target: DRONE_TOKEN
    when:
      event: deployment
      environment: staging

  synch_production_secrets:
    image: quay.io/ukhomeofficedigital/cop-secrets
    environment:
      - DRONE_SERVER=https://drone.acp.homeoffice.gov.uk
    secrets:
      - source: PRODUCTION_DRONE_AWS_ACCESS_KEY_ID
        target: AWS_ACCESS_KEY_ID
      - source: PRODUCTION_DRONE_AWS_SECRET_ACCESS_KEY
        target: AWS_SECRET_ACCESS_KEY
      - source: DRONE_PUBLIC_TOKEN
        target: DRONE_TOKEN
    when:
      event: deployment
      environment: production

  image_to_quay:
    image: quay.io/ukhomeofficedigital/drone-docker
    secrets:
      - source: QUAY_PASSWORD
        target: DOCKER_PASSWORD
      - source: QUAY_USERNAME
        target: DOCKER_USERNAME
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/ref-data-gov-tool
    tags:
      - ${DRONE_COMMIT_SHA}
    when:
      branch: master
      event: push

  deploy_to_dev:
    image: quay.io/ukhomeofficedigital/kd
    secrets:
      - source: DEV_API_REF_PROTOCOL
        target: API_REF_PROTOCOL
      - source: DEV_API_REF_URL
        target: API_REF_URL
      - source: DEV_ENVIRONMENT
        target: ENVIRONMENT
      - source: DEV_KEYCLOAK_PROTOCOL
        target: KEYCLOAK_PROTOCOL
      - source: DEV_KEYCLOAK_REALM
        target: KEYCLOAK_REALM
      - source: DEV_KEYCLOAK_URL
        target: KEYCLOAK_URL
      - source: DEV_KUBE_SERVER
        target: KUBE_SERVER
      - source: DEV_KUBE_TOKEN
        target: KUBE_TOKEN
      - source: WWW_REF_IMAGE
        target: WWW_REF_IMAGE
      - source: WWW_REF_KEYCLOAK_CLIENT_ID
        target: WWW_REF_KEYCLOAK_CLIENT_ID
      - source: DEV_WWW_REF_KUBE_NAMESPACE
        target: WWW_REF_KUBE_NAMESPACE
      - source: WWW_REF_NAME
        target: WWW_REF_NAME
      - source: WWW_REF_PORT
        target: WWW_REF_PORT
      - source: WWW_REF_PROTOCOL
        target: WWW_REF_PROTOCOL
      - source: DEV_WWW_REF_READ_ONLY_MODE
        target: WWW_REF_READ_ONLY_MODE
      - source: DEV_WWW_REF_URL
        target: WWW_REF_URL
      - source: NGINX_IMAGE
        target: NGINX_IMAGE
      - source: NGINX_TAG
        target: NGINX_TAG
    commands:
      - WWW_REF_TAG=$${DRONE_COMMIT_SHA}
      - kd --insecure-skip-tls-verify -f kube/cert.yml -f kube/secret.yml -f kube/deployment.yml -f kube/service.yml -f kube/ingress.yml -f kube/network-policy.yml
    when:
      branch: master
      event: push

  deploy_to_staging:
    image: quay.io/ukhomeofficedigital/kd
    secrets:
      - source: STAGING_API_REF_PROTOCOL
        target: API_REF_PROTOCOL
      - source: STAGING_API_REF_URL
        target: API_REF_URL
      - source: STAGING_ENVIRONMENT
        target: ENVIRONMENT
      - source: STAGING_KEYCLOAK_PROTOCOL
        target: KEYCLOAK_PROTOCOL
      - source: STAGING_KEYCLOAK_REALM
        target: KEYCLOAK_REALM
      - source: STAGING_KEYCLOAK_URL
        target: KEYCLOAK_URL
      - source: STAGING_KUBE_SERVER
        target: KUBE_SERVER
      - source: STAGING_KUBE_TOKEN
        target: KUBE_TOKEN
      - source: WWW_REF_IMAGE
        target: WWW_REF_IMAGE
      - source: WWW_REF_KEYCLOAK_CLIENT_ID
        target: WWW_REF_KEYCLOAK_CLIENT_ID
      - source: STAGING_WWW_REF_KUBE_NAMESPACE
        target: WWW_REF_KUBE_NAMESPACE
      - source: WWW_REF_NAME
        target: WWW_REF_NAME
      - source: WWW_REF_PORT
        target: WWW_REF_PORT
      - source: WWW_REF_PROTOCOL
        target: WWW_REF_PROTOCOL
      - source: STAGING_WWW_REF_READ_ONLY_MODE
        target: WWW_REF_READ_ONLY_MODE
      - source: STAGING_WWW_REF_URL
        target: WWW_REF_URL
      - source: NGINX_IMAGE
        target: NGINX_IMAGE
      - source: NGINX_TAG
        target: NGINX_TAG
    commands:
      - WWW_REF_TAG=$${DRONE_COMMIT_SHA}
      - kd --insecure-skip-tls-verify -f kube/cert.yml -f kube/secret.yml -f kube/deployment.yml -f kube/service.yml -f kube/ingress.yml -f kube/network-policy.yml
    when:
      event: deployment
      environment: staging

  deploy_to_prod:
    image: quay.io/ukhomeofficedigital/kd
    secrets:
      - source: PRODUCTION_API_REF_PROTOCOL
        target: API_REF_PROTOCOL
      - source: PRODUCTION_API_REF_URL
        target: API_REF_URL
      - source: PRODUCTION_ENVIRONMENT
        target: ENVIRONMENT
      - source: PRODUCTION_KEYCLOAK_PROTOCOL
        target: KEYCLOAK_PROTOCOL
      - source: PRODUCTION_KEYCLOAK_REALM
        target: KEYCLOAK_REALM
      - source: PRODUCTION_KEYCLOAK_URL
        target: KEYCLOAK_URL
      - source: PRODUCTION_KUBE_SERVER
        target: KUBE_SERVER
      - source: PRODUCTION_KUBE_TOKEN
        target: KUBE_TOKEN
      - source: WWW_REF_IMAGE
        target: WWW_REF_IMAGE
      - source: WWW_REF_KEYCLOAK_CLIENT_ID
        target: WWW_REF_KEYCLOAK_CLIENT_ID
      - source: PRODUCTION_WWW_REF_KUBE_NAMESPACE
        target: WWW_REF_KUBE_NAMESPACE
      - source: WWW_REF_NAME
        target: WWW_REF_NAME
      - source: WWW_REF_PORT
        target: WWW_REF_PORT
      - source: WWW_REF_PROTOCOL
        target: WWW_REF_PROTOCOL
      - source: PRODUCTION_WWW_REF_READ_ONLY_MODE
        target: WWW_REF_READ_ONLY_MODE
      - source: PRODUCTION_WWW_REF_URL
        target: WWW_REF_URL
      - source: NGINX_IMAGE
        target: NGINX_IMAGE
      - source: NGINX_TAG
        target: NGINX_TAG
    commands:
      - WWW_REF_TAG=$${DRONE_COMMIT_SHA}
      - kd --insecure-skip-tls-verify -f kube/cert.yml -f kube/secret.yml -f kube/deployment.yml -f kube/service.yml -f kube/ingress.yml -f kube/network-policy.yml
    when:
      event: deployment
      environment: production

  notify:
    image: plugins/slack
    secrets: [ SLACK_WEBHOOK ]
    channel: cop-deployments
    username: Drone Build Watcher
    template: >
      {{#build.deployTo}}
        *{{repo.name}} - Build {{build.number}} - {{uppercasefirst build.deployTo}} - {{uppercase build.status}}*
        {{build.link}}
      {{else}}
        *{{repo.name}} - Build {{build.number}} - Development - {{uppercase build.status}}*
        {{build.link}}
      {{/build.deployTo}}
    when:
      branch: master
      event: [ push, deployment ]
      status: [ success, failure ]
