pipeline:

  install:
    image: quay.io/ukhomeofficedigital/node-10
    commands:
      - node -v
      - npm -v
      - npm install --silent
    when:
      event: push

  unit_tests:
    image: quay.io/ukhomeofficedigital/node-10
    commands:
      - npm run test
    when:
      event: push

  build:
    image: quay.io/ukhomeofficedigital/drone-docker
    commands:
      - docker build -t ref-data-gov-tool:$${DRONE_COMMIT_SHA} .
    when:
      event: push

  image_to_quay:
    image: quay.io/ukhomeofficedigital/drone-docker
    secrets:
      - DOCKER_PASSWORD
      - DOCKER_USERNAME
    registry: quay.io
    repo: quay.io/ukhomeofficedigital/ref-data-gov-tool
    tags:
      - ${DRONE_BUILD_NUMBER}
      - ${DRONE_COMMIT_SHA}
      - latest
    when:
      branch: master
      event: push

  deploy_to_dev:
    image: quay.io/ukhomeofficedigital/kd
    secrets:
      - DEV_API_BASE_URL
      - DEV_ENVIRONMENT
      - DEV_HOSTNAME
      - DEV_KEYCLOAK_AUTH_URL
      - DEV_KEYCLOAK_CLIENT_ID
      - DEV_KEYCLOAK_REALM
      - DEV_KUBE_NAMESPACE
      - DEV_KUBE_SERVER
      - DEV_KUBE_TOKEN
      - DEV_READ_ONLY_MODE
    commands:
      - export API_BASE_URL=$${DEV_API_BASE_URL}
      - export ENVIRONMENT=$${DEV_ENVIRONMENT}
      - export HOSTNAME=$${DEV_HOSTNAME}
      - export KEYCLOAK_AUTH_URL=$${DEV_KEYCLOAK_AUTH_URL}
      - export KEYCLOAK_CLIENT_ID=$${DEV_KEYCLOAK_CLIENT_ID}
      - export KEYCLOAK_REALM=$${DEV_KEYCLOAK_REALM}
      - export KUBE_NAMESPACE=$${DEV_KUBE_NAMESPACE}
      - export KUBE_SERVER=$${DEV_KUBE_SERVER}
      - export KUBE_TOKEN=$${DEV_KUBE_TOKEN}
      - export READ_ONLY_MODE=$${DEV_READ_ONLY_MODE}
      - kd --insecure-skip-tls-verify -f kube/secret.yml -f kube/deployment.yml -f kube/service.yml -f kube/ingress.yml -f kube/network-policy.yml
    when:
      branch: master
      event: push

  deploy_to_staging:
    image: quay.io/ukhomeofficedigital/kd
    secrets:
      - STAGING_API_BASE_URL
      - STAGING_ENVIRONMENT
      - STAGING_HOSTNAME
      - STAGING_KEYCLOAK_AUTH_URL
      - STAGING_KEYCLOAK_CLIENT_ID
      - STAGING_KEYCLOAK_REALM
      - STAGING_KUBE_NAMESPACE
      - STAGING_KUBE_SERVER
      - STAGING_KUBE_TOKEN
      - STAGING_READ_ONLY_MODE
    commands:
      - export API_BASE_URL=$${STAGING_API_BASE_URL}
      - export ENVIRONMENT=$${STAGING_ENVIRONMENT}
      - export HOSTNAME=$${STAGING_HOSTNAME}
      - export KEYCLOAK_AUTH_URL=$${STAGING_KEYCLOAK_AUTH_URL}
      - export KEYCLOAK_CLIENT_ID=$${STAGING_KEYCLOAK_CLIENT_ID}
      - export KEYCLOAK_REALM=$${STAGING_KEYCLOAK_REALM}
      - export KUBE_NAMESPACE=$${STAGING_KUBE_NAMESPACE}
      - export KUBE_SERVER=$${STAGING_KUBE_SERVER}
      - export KUBE_TOKEN=$${STAGING_KUBE_TOKEN}
      - export READ_ONLY_MODE=$${STAGING_READ_ONLY_MODE}
      - kd --insecure-skip-tls-verify -f kube/secret.yml -f kube/deployment.yml -f kube/service.yml -f kube/ingress.yml -f kube/network-policy.yml
    when:
      event: deployment
      environment: staging

  deploy_to_prod:
    image: quay.io/ukhomeofficedigital/kd
    secrets:
      - PROD_API_BASE_URL
      - PROD_ENVIRONMENT
      - PROD_HOSTNAME
      - PROD_KEYCLOAK_AUTH_URL
      - PROD_KEYCLOAK_CLIENT_ID
      - PROD_KEYCLOAK_REALM
      - PROD_KUBE_NAMESPACE
      - PROD_KUBE_SERVER
      - PROD_KUBE_TOKEN
      - PROD_READ_ONLY_MODE
    commands:
      - export API_BASE_URL=$${PROD_API_BASE_URL}
      - export ENVIRONMENT=$${PROD_ENVIRONMENT}
      - export HOSTNAME=$${PROD_HOSTNAME}
      - export KEYCLOAK_AUTH_URL=$${PROD_KEYCLOAK_AUTH_URL}
      - export KEYCLOAK_CLIENT_ID=$${PROD_KEYCLOAK_CLIENT_ID}
      - export KEYCLOAK_REALM=$${PROD_KEYCLOAK_REALM}
      - export KUBE_NAMESPACE=$${PROD_KUBE_NAMESPACE}
      - export KUBE_SERVER=$${PROD_KUBE_SERVER}
      - export KUBE_TOKEN=$${PROD_KUBE_TOKEN}
      - export READ_ONLY_MODE=$${PROD_READ_ONLY_MODE}
      - kd --insecure-skip-tls-verify -f kube/secret.yml -f kube/deployment.yml -f kube/service.yml -f kube/ingress.yml -f kube/network-policy.yml
    when:
      event: deployment
      environment: production
