---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{.WWW_REF_NAME}}-ingress
  labels:
    stable.k8s.psg.io/kcm.class: default
  annotations:
    kubernetes.io/ingress.class: "nginx-external"
    ingress.kubernetes.io/backend-protocol: "HTTPS"
    stable.k8s.psg.io/kcm.provider: http
spec:
  rules:
  - host: {{.WWW_REF_URL}}
    http:
      paths:
      - backend:
          serviceName: {{.WWW_REF_NAME}}-service
          servicePort: 10443
        path: /
  tls:
  - hosts:
    - {{.WWW_REF_URL}}
    secretName: {{.WWW_REF_URL}}-tls
